name: "semver-gist"
description: manages versioning using semantic versioning through gist.
branding:
  icon: play
  color: gray-dark
inputs:
  action:
    description: "Action type"
    required: true
    default: "next"
  token:
    description: "Token for authorized requests"
    required: true
  gist_id:
    description: "Gist id used on action"
    required: true
  package_name:
    description: "Name of the package used on action"
    required: true
  release_type:
    description: "Type of the release"
    default: "prerelease"
  identifier:
    description: "Release idetentifier"
    default: "dev"
  identifier_base:
    description: "Base value for the idetentifier"
    default: "0"
  snapshot:
    description: "Snapshot of the increment action"
outputs:
  version:
    description: "The incremented version of the package"
  snapshot:
    description: "Snapshot of the increment action"
runs:
  using: "node20"
  main: "dist/index.js"
